# -*- coding: utf-8 -*-
"""
Created on 2025.07.19

@author: MiniUFO
Copyright 2018. All rights reserved. Use is subject to license terms.
"""
import os
import numpy as np
import xarray as xr
import pytest
from xdispersion.core import RelativeDispersion
from xdispersion.measures import (
    relative_dispersion,
    velocity_structure_function,
    relative_diffusivity,
    finite_amplitude_growth_rate,
    initial_memory,
    anisotropy,
    lagrangian_velocity_correlation,
    kurtosis,
    cencini_vulpiani_exponent,
    finite_size_lyapunov_exponent,
    cumulative_inverse_separation_time,
    probability_density_function,
    cumulative_density_function,
    principle_axis_components,
    rotational_divergent_components,
)
from xdispersion.template import cal_measures
from xdispersion.utils import gen_rbins


rbins = gen_rbins(0.01, 1000, alpha=1.2)

# Chunk sizes: test that the ``chunk`` parameter works for both ragged
# (block-by-block pair generation) and non-ragged (dask pair chunking)
# paths.  These are intentionally smaller than the total pair count so
# that multi-chunk code paths are exercised.
RAGGED_CHUNK   = 50    # trajectories per block in _get_all_chunked
NONRAGGED_CHUNK = 200  # pairs per dask chunk

# All measure names produced by cal_measures (see template.py MEASURES).
# Used to parametrise the golden-file comparison test.
ALL_MEASURE_NAMES = [
    # --- const-t ---
    'r2_t', 'rpb2_t', 'S2_t', 'S2ll_t', 'S2tr_t', 'S3_t', 'a2_t',
    'K2_t', 'K2p_t', 'FAGR_t', 'FAGRp_t',
    'imrv_t', 'imrv2_t', 'imra_t',
    'aniso_t', 'LVC_t', 'LAC_t',
    'ku_t', 'kupb_t', 'CVE_t',
    # --- const-r ---
    'r2_r', 'rpb2_r', 'S2_r', 'S2ll_r', 'S2tr_r', 'S3_r', 'a2_r',
    'K2_r', 'K2p_r', 'FAGR_r', 'FAGRp_r',
    'imrv_r', 'imrv2_r', 'imra_r',
    'aniso_r', 'LVC_r', 'LAC_r',
    'CVE_r', 'FSLE_r', 'CIST_r',
    # --- derived ---
    'S2rr_r', 'S2dd_r',
]


# --------------------------------------------------------------------------- #
#  Module-scoped parametrised fixture                                         #
#                                                                             #
#  Builds RelativeDispersion with a *chunk* parameter so that the             #
#  chunked code paths (``_get_all_chunked`` for ragged, dask pair             #
#  chunking for non-ragged) are exercised.  Building blocks are NOT           #
#  .load()-ed — they are computed lazily inside cal_measures.                 #
#                                                                             #
#  The reference NC file (pre-generated by generate_ref.py) is also           #
#  loaded for golden-file comparison.                                         #
# --------------------------------------------------------------------------- #
@pytest.fixture(scope='module', params=['ragged', 'local', 'nonlocal'])
def ctx(request):
    if request.param == 'ragged':
        dset = xr.open_dataset('./data/glad32.nc')
        rd = RelativeDispersion(dset, xpos='longitude', ypos='latitude',
                                uvel='ve', vvel='vn', maxtlen=4 * 24 * 80,
                                time='time', Rearth=6371.2, ID='traj',
                                coord='latlon', ragged=True,
                                chunk=RAGGED_CHUNK)
        p_all = rd.get_all_pairs()
        pairs = rd.get_original_pairs(p_all, r0=[0.08, 0.18])
        assert len(pairs.pair) == 171
    elif request.param == 'local':
        dset = xr.open_dataset('./data/Particles_local.nc')
        rd = RelativeDispersion(dset, xpos='xpos', ypos='ypos',
                                uvel='uvel', vvel='vvel',
                                time='time', ID='ID',
                                coord='cartesian', ragged=False,
                                chunk=NONRAGGED_CHUNK)
        p_all = rd.get_all_pairs()
        pairs = rd.get_original_pairs(p_all, r0=[0, 0.01])
        assert len(pairs.pair) == 2920
    else:
        dset = xr.open_dataset('./data/Particles_nonlocal.nc')
        rd = RelativeDispersion(dset, xpos='xpos', ypos='ypos',
                                uvel='uvel', vvel='vvel',
                                time='time', ID='ID',
                                coord='cartesian', ragged=False,
                                chunk=NONRAGGED_CHUNK)
        p_all = rd.get_all_pairs()
        pairs = rd.get_original_pairs(p_all, r0=[0, 0.01])
        assert len(pairs.pair) == 2920

    ref_path = f'./data/ref_measures_{request.param}.nc'
    if not os.path.exists(ref_path):
        pytest.fail(
            f'Reference file {ref_path} not found.\n'
            f'Run  python tests/generate_ref.py  first to generate it.'
        )
    ref = xr.open_dataset(ref_path)

    # Compute all measures once (building blocks are computed inside
    # cal_measures, not .load()-ed in the fixture).
    measures = cal_measures(rd, pairs, rbins, one_by_one=True).load()

    return {
        'kind'   : request.param,
        'rd'     : rd,
        'pairs'  : pairs,
        'ref'    : ref,
        'measures': measures,
    }


# --------------------------------------------------------------------------- #
#  Helper for golden-file comparison                                          #
# --------------------------------------------------------------------------- #
def _assert_close(result_vals, ref_vals, rtol=2e-3, atol=1e-6):
    """Compare two arrays, ignoring positions where either is NaN/inf.

    ``atol`` handles near-zero values where chunked (dask) vs. in-memory
    (numpy) computation order produces tiny floating-point differences
    that inflate the *relative* error.
    """
    result_vals = np.asarray(result_vals, dtype=float)
    ref_vals    = np.asarray(ref_vals,    dtype=float)
    valid = np.isfinite(ref_vals) & np.isfinite(result_vals)
    if valid.any():
        np.testing.assert_allclose(
            result_vals[valid], ref_vals[valid], rtol=rtol, atol=atol,
        )


# --------------------------------------------------------------------------- #
#  Golden-file comparison: every measure from cal_measures                    #
# --------------------------------------------------------------------------- #
@pytest.mark.parametrize('measure_name', ALL_MEASURE_NAMES)
def test_measure_against_reference(ctx, measure_name):
    """Compare a single measure computed via cal_measures against the
    pre-generated reference NC file."""
    ref = ctx['ref']
    measures = ctx['measures']

    assert measure_name in measures.data_vars, \
        f'{measure_name} missing from cal_measures output'
    assert measure_name in ref.data_vars, \
        f'{measure_name} missing from reference NC'

    _assert_close(measures[measure_name].values, ref[measure_name].values)


# --------------------------------------------------------------------------- #
#  Physical-constraint checks (sanity, not golden-file)                       #
# --------------------------------------------------------------------------- #
def test_physical_constraints(ctx):
    """Verify key physical properties for a subset of measures."""
    m = ctx['measures']

    # relative dispersion > 0
    for name in ['r2_t', 'r2_r']:
        v = m[name].values
        v = v[np.isfinite(v)]
        assert (v > 0).all(), f'{name} has non-positive values'

    # structure functions >= 0
    for name in ['S2_t', 'S2_r']:
        v = m[name].values
        v = v[np.isfinite(v)]
        assert (v >= 0).all(), f'{name} has negative values'

    # kurtosis >= 1  (Cauchy-Schwarz:  <r^4>/<r^2>^2 >= 1)
    for name in ['ku_t']:
        v = m[name].values
        v = v[np.isfinite(v)]
        assert (v >= 1.0).all(), f'{name} < 1'

    # anisotropy >= 1  (ra >= rb  =>  sqrt(ra/rb) >= 1)
    for name in ['aniso_t', 'aniso_r']:
        v = m[name].values
        v = v[np.isfinite(v)]
        assert (v >= 1.0).all(), f'{name} < 1'

    # Lagrangian correlations in [-1, 1]
    for name in ['LVC_t', 'LVC_r', 'LAC_t', 'LAC_r']:
        v = m[name].values
        v = v[np.isfinite(v)]
        assert (v >= -1.01).all() and (v <= 1.01).all(), f'{name} out of [-1, 1]'


# --------------------------------------------------------------------------- #
#  Edge-case tests: exceptions for invalid parameters                         #
# --------------------------------------------------------------------------- #
def test_fsle_raises_on_const_t(ctx):
    """FSLE only supports const-r; const-t should raise."""
    rd, pairs = ctx['rd'], ctx['pairs']
    _, _, _, r, _ = rd.separation_measures(pairs)
    with pytest.raises(Exception):
        finite_size_lyapunov_exponent(r, rbins=rbins, mean_at='const-t')


def test_fsle_raises_on_invalid_interpT(ctx):
    """interpT must be a positive integer."""
    rd, pairs = ctx['rd'], ctx['pairs']
    _, _, _, r, _ = rd.separation_measures(pairs)
    with pytest.raises(Exception):
        finite_size_lyapunov_exponent(r, rbins=rbins,
                                      mean_at='const-r', interpT=0)


def test_cist_raises_on_const_t(ctx):
    """CIST only supports const-r; const-t should raise."""
    rd, pairs = ctx['rd'], ctx['pairs']
    _, _, _, r, _ = rd.separation_measures(pairs)
    with pytest.raises(Exception):
        cumulative_inverse_separation_time(r, mean_at='const-t')


# --------------------------------------------------------------------------- #
#  PDF & CDF (not included in cal_measures)                                   #
# --------------------------------------------------------------------------- #
def test_pdf_and_cdf(ctx):
    """Test probability_density_function and cumulative_density_function."""
    rd, pairs = ctx['rd'], ctx['pairs']
    _, _, _, r, _ = rd.separation_measures(pairs)

    # PDF
    PDF = probability_density_function(r, rbins=rbins)
    assert PDF.name == 'PDF'
    assert 'rbin' in PDF.dims
    valid = PDF.values[~np.isnan(PDF.values)]
    assert (valid >= 0).all()

    # CDF (auto bin-width)
    CDF = cumulative_density_function(PDF)
    assert CDF.name == 'CDF'
    assert 'rbin' in CDF.dims
    # CDF should be non-decreasing along rbin (not across rtime)
    diffs = CDF.diff('rbin')
    valid = np.isfinite(diffs.values)
    if valid.any():
        assert (diffs.values[valid] >= -1e-6).all(), 'CDF is decreasing along rbin'

    # CDF with explicit bin_edges
    CDF2 = cumulative_density_function(PDF, bin_edges=rbins.values)
    assert CDF2.name == 'CDF'


# --------------------------------------------------------------------------- #
#  Helper: principle_axis_components                                          #
# --------------------------------------------------------------------------- #
def test_principle_axis_components(ctx):
    """Test principle_axis_components helper."""
    rd, pairs = ctx['rd'], ctx['pairs']
    rx, ry, rxy, _, _ = rd.separation_measures(pairs)

    rx2m = (rx ** 2).mean('pair')
    ry2m = (ry ** 2).mean('pair')
    rxym = rxy.mean('pair')

    ra2, rb2, ang = principle_axis_components(rx2m, ry2m, rxym)

    # ra2 >= rb2  (major >= minor)
    valid = ~np.isnan(ra2.values)
    assert (ra2.values[valid] >= rb2.values[valid] - 1e-6).all()

    # trace preserved:  ra2 + rb2 == rx2m + ry2m
    np.testing.assert_allclose(
        ra2.values[valid] + rb2.values[valid],
        (rx2m + ry2m).values[valid], rtol=1e-4,
    )


# --------------------------------------------------------------------------- #
#  Helper: rotational_divergent_components                                     #
# --------------------------------------------------------------------------- #
def test_rotational_divergent_components(ctx):
    """Test rotational_divergent_components helper and compare against
    the S2rr_r / S2dd_r values in the reference NC."""
    rd, pairs = ctx['rd'], ctx['pairs']
    ref = ctx['ref']

    _, _, _, r, _ = rd.separation_measures(pairs)
    _, _, dul, dut, _, _, _ = rd.velocity_measures(pairs)

    S2ll = velocity_structure_function(dul, r, rbins=rbins, mean_at='const-r')
    S2tr = velocity_structure_function(dut, r, rbins=rbins, mean_at='const-r')

    S2rr, S2dd = rotational_divergent_components(S2ll, S2tr)
    assert S2rr.name == 'S2rr'
    assert S2dd.name == 'S2dd'
    assert 'rbin' in S2rr.dims

    # Compare against reference (align coordinates — rbin may differ
    # because rotational_divergent_components uses diff which shifts coords)
    for test_da, ref_name in [(S2rr, 'S2rr_r'), (S2dd, 'S2dd_r')]:
        ref_da = ref[ref_name]
        common = np.intersect1d(test_da.rbin.values, ref_da.rbin.values)
        if len(common) > 0:
            _assert_close(
                test_da.sel(rbin=common).values,
                ref_da.sel(rbin=common).values,
            )

    # trace preserved: S2rr + S2dd == S2ll + S2tr (where both finite)
    # Note: S2rr/S2dd may have fewer rbin coords than S2ll/S2tr due to
    # diff() inside rotational_divergent_components; align with inner join.
    total_rd = S2rr + S2dd
    total_lt = S2ll + S2tr
    aligned_rd, aligned_lt = xr.align(total_rd, total_lt, join='inner')
    valid = np.isfinite(aligned_rd.values) & np.isfinite(aligned_lt.values)
    if valid.any():
        np.testing.assert_allclose(
            aligned_rd.values[valid], aligned_lt.values[valid], rtol=1e-4,
        )


# --------------------------------------------------------------------------- #
#  Individual function: output naming verification                             #
#  (ensures each function returns the expected DataArray name)                #
# --------------------------------------------------------------------------- #
def test_output_naming(ctx):
    """Verify that each measure function returns the expected name."""
    rd, pairs = ctx['rd'], ctx['pairs']
    rx, ry, rxy, r, rpb = rd.separation_measures(pairs)
    du, dv, dul, dut, vmi, vmj, uv = rd.velocity_measures(pairs)
    dax, day, _, _, ai, aj, axy = rd.acceleration_measures(pairs)

    assert relative_dispersion(r, order=2, mean_at='const-t').name == 'r2_t'
    assert relative_dispersion(r, order=2, mean_at='const-r',
                               rbins=rbins).name == 'r2_r'
    assert velocity_structure_function(np.hypot(du, dv), r,
                                       mean_at='const-t').name == 'S2_t'
    assert velocity_structure_function(np.hypot(du, dv), r, rbins=rbins,
                                       mean_at='const-r').name == 'S2_r'
    assert relative_diffusivity(r, mean_at='const-t').name == 'K2_t'
    assert relative_diffusivity(r, mean_at='const-r',
                                rbins=rbins).name == 'K2_r'
    assert finite_amplitude_growth_rate(r, mean_at='const-t',
                                        samples='all').name == 'FAGRa_t'
    assert finite_amplitude_growth_rate(r, mean_at='const-t',
                                        samples='positive').name == 'FAGRp_t'
    assert initial_memory(rx, ry, du, dv, r,
                          mean_at='const-t').name == 'initm_t'
    assert anisotropy(rx, ry, rxy, r, mean_at='const-t').name == 'aniso_t'
    assert lagrangian_velocity_correlation(uv, vmi, vmj, r,
                                           mean_at='const-t').name == 'lvc_t'
    assert kurtosis(r, mean_at='const-t').name == 'Ku_t'
    assert cencini_vulpiani_exponent(r, mean_at='const-t').name == 'CVE_t'
    assert finite_size_lyapunov_exponent(r, rbins=rbins,
                                         mean_at='const-r').name == 'FSLE_r'
    assert cumulative_inverse_separation_time(r, rbins=rbins,
                                              mean_at='const-r').name == 'CIST_r'
